### PR TITLE
Added preliminary buoy finder class

### PR DESCRIPTION
**Pull request by edinpeter**
_shatters the commit record from last year_

### CODE REVIEW

**Comment by JustBenj** [comment]
This is a good start. Commits are good. We'll want to have something a little more complete and fully tested before merging. I.e. a "find buoy" action that publishes the buoy position.

**Comment by edinpeter** [comment]
No ros to compile / test one :(

**Comment by JustBenj** [comment]
@edinpeter Sounds like a job for some new members maybe?

**Comment by edinpeter** [comment]
I think I should have a non-zero understanding prior to teaching, but that's just my opinion

**Comment by iConor** [comment]
@edinpeter That's alright, you don't have to teach. We'll be generating an API others can refer to when using the library.

**Pull request closed without merging**
